#!/bin/bash
cd "$(dirname "$0")"
./node_modules/node/bin/node main.js
#!/bin/bash
cd "$(dirname "$0")"
./node_modules/node/bin/node main.js
#!/bin/bash
cd "$(dirname "$0")"
./node_modules/node/bin/node main.js
